server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: aki-web-backend
  security:
    user:
      name: admin
      password: asdf

  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**

  web:
    resources:
      # fix: 图片上传成功后访问404，无法回显
      # TODO 在linux上要改路径
      static-locations: file:D:/dev/project/AkiWeb/aki-web-backend/src/main/resources/static/
  #      - classpath:/META-INF/resources/
  #      - classpath:/resources/
  #      - classpath:/static/
  #      - classpath:/public/
  #      - classpath:/webapp/

# DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aki
    username: root
    password: 123456789

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: pub.akiwebbackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn