server:
  address: 0.0.0.0
  port: 8877
  tomcat:
    max-swallow-size: 100MB

spring:
  application:
    name: aki-web
  security:
    user:
      name: admin
      password: asdf
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 100MB
      max-request-size: 100MB

  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**

  web:
    resources:
      # fix: 图片上传成功后访问404，无法回显
      static-locations: /home/cym/app/aki-web/nginx/html/static/images
  #      - classpath:/META-INF/resources/
  #      - classpath:/resources/
  #      - classpath:/static/
  #      - classpath:/public/
  #      - classpath:/webapp/

# DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/aki-web
    username: root
    password: asdf

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: pub.akiwebbackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn