version: "3.8"
services:
  aki-web:
    restart: always
    build:
      context: .
    container_name: aki-web-backend
    ports:
      - 8877:8877
    volumes:
      - ./nginx/html/static/images:/app/nginx/html/static/images
      - ./app.jar:/app/app.jar:z
    depends_on:
      - db
      - nginx
    privileged: true
  db:
    image: mysql:8.0
    ports:
      - 3306:3306 # 真上线不要暴露出来
    container_name: aki-web-db
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    environment:
      MYSQL_DATABASE: aki-web
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: asdf
      # TZ: Asia/Shanghai
  nginx:
    image: nginx:latest
    container_name: aki-web-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true